### ISSUE TITLE
problem with open a project

### ISSUE THREAD

**Issue by jakubaugusty** [microsoft/HoloLens-ResearchMode-Unreal#13]
Hello, I have a problem with open a project in UE 5.0:
![image](https://github.com/microsoft/HoloLens-ResearchMode-Unreal/assets/101868974/f9ac7b39-7a9a-4f77-a1f9-08822172d1f9)
![image](https://github.com/microsoft/HoloLens-ResearchMode-Unreal/assets/101868974/a5dbd516-6865-4d93-b9bf-00391c842a9f)
![image](https://github.com/microsoft/HoloLens-ResearchMode-Unreal/assets/101868974/b1891163-2fe4-43cd-8860-a0e57e2d8d56)
![image](https://github.com/microsoft/HoloLens-ResearchMode-Unreal/assets/101868974/d8417e33-db69-4754-95c3-4b56fb0a550b)

What's wrong?

**Comment by TaniaChistyakova** [comment]
You must enable Hololens plugin in Unreal to develop app for HL. Please look to

https://learn.microsoft.com/en-us/windows/mixed-reality/develop/unreal/unreal-quickstart

**Comment by jakubaugusty** [comment]
Already there is no HoloLens plugin in UE 5+ in edit>plugins>Augmented Reality. Its only in 4.27.2.

**Comment by TaniaChistyakova** [comment]
This plugin is for 5.0 and 5.1

https://unrealengine.com/marketplace/en-US/product/ef8930ca860148c498b46887da196239

https://github.com/microsoft/Microsoft-OpenXR-Unreal

**Comment by jakubaugusty** [comment]
Sorry for my inquisitiveness, I have the OpenXR plugin unlocked in my UE5 but it still shows me the HololensAR plugin error as in the first message. I'm so desperate that I tested it on two more UE versions but the problem is basically the same. I am sending a snippet from the logs:

ERROR: Unable to find plugin 'HoloLensAR' (referenced via HL2App.uproject). Install it and try again, or remove it from the required plugin list.
BuildException: Unable to find plugin 'HoloLensAR' (referenced via HL2App.uproject). Install it and try again, or remove it from the required plugin list.
