### ISSUE TITLE
is there a way to access the front facing camera in Unreal?

### ISSUE THREAD

**Issue by ARtSSt** [microsoft/HoloLens-ResearchMode-Unreal#5]
I see in the docs this allows for grabbing all the sensor cameras upper right and left Cameras and depth. But I can find no way to grab the front facing camera feed or even pull frames in Unreal. 

Is this possible?

**Comment by TaniaChistyakova** [comment]
Yes, it is possible, but out of the plugin's scope. Please look to the Unreal Mixed Reality docs.

https://docs.microsoft.com/en-gb/windows/mixed-reality/develop/unreal/unreal-hololens-camera?tabs=426

**Comment by ARtSSt** [comment]
Thx Andrey, follow-up question in regards to the L/R cameras

we we haven't been able to retrieve pixel data from ARTexture from these cameras. The UARTexture comes from Utexture and we seem to only get null errors using the >GetRunningPlatformData(), we receive a double pointer function that returns null. 

We are trying to get the pixel array to feed in openCV we have compiled for unreal and hololens2.

**Comment by TaniaChistyakova** [comment]
Unreal doesn't give access to pixel data from ARTexture. But you can add your own code to UHololensVLCCam::SensorLoop() in this plugin. Look to the loop on 82-102 lines.
