### ISSUE TITLE
Package for ARM

### ISSUE THREAD

**Issue by gvindiol** [microsoft/HoloLens-ResearchMode-Unreal#6]
> Added arm32 support for Research Mode.
https://docs.microsoft.com/en-us/hololens/hololens-release-notes#windows-holographic-version-20h2---january-2021-update

Is there a process in Unreal to package a Hololens2 Project for ARM32 and not ARM64?
I'm seeing this done in Unity only.

I change the Target Platform to Hololens.
(Target.Platform == UnrealTargetPlatform.HoloLens)

`UATHelper: Packaging (HoloLens):   Using ARM64 architecture for deploying to HoloLens device`

**Comment by TaniaChistyakova** [comment]
Epic's Unreal Engine doesn't support ARM32 at all. 

Hololens supports ARM32 for compatibility mode only, it's advised not to use ARM32 for a new app.
