### ISSUE TITLE
Broadcasting the sensors stream to PC

### ISSUE THREAD

**Issue by evia100** [microsoft/HoloLens-ResearchMode-Unreal#8]
Hi,

I am working on a ML project and I want to use the data from the sensors ( especially the PV and AHAT sensors). Is there an option to broadcast the data in real time using tcp/udp and save it to my PC? I tried working with the stream recorder from the opencv4HoloLens2 repo but it is not scaleable, the storage in the device is capable of storing only 2-3 recordings of 2-3 minutes (and when the storage is full the app crashes without a warning and the record is corrupted).

Hope to get an helpful answer.
Thank in advance!
Eviatar.

**Comment by TaniaChistyakova** [comment]
Hi, the plugin hasn't any embedded streaming option. You should implement streaming by yourself. You can use any streaming lib and any network protocol.
